#!/usr/bin/env bash

echo "Setting up dev environment..."

# Do the following on MacOS only
if [[ $(uname) == "Darwin" ]]; then
    echo "MacOS Detected"
    # Install brew
    if ! command -v brew >/dev/null 2>&1; then
        echo "Installing Homebrew..."
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    else
        echo "Homebrew already installed, updating..."
        brew update
    fi        

    # Install allthethings with Brewfile
    echo "Installing packages and apps with Homebrew, cask and mas..."
    brew bundle --file=util/Brewfile

fi

#### Shell (zsh) configuration ####
# Install Oh My Zsh
if [[ ! -d $HOME/.oh-my-zsh ]]; then
    # Install Oh My Zsh
    echo "Installing Oh My Zsh..."
    RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
else
    # Use the inbuilt mechanism to update Oh My Zsh
    echo "Oh My Zsh already installed, updating..."
    cd $HOME/.oh-my-zsh
    git pull
    cd $HOME/dotfiles
fi

# Install Powerlevel9k zsh theme
if [[ ! -d $HOME/.oh-my-zsh/custom/themes/powerlevel10k ]]; then
    echo "Installing Powerlevel10k zsh theme..."
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $HOME/.oh-my-zsh/custom/themes/powerlevel10k
else
    echo "Powerlevel10k already installed, updating..."
    cd $HOME/.oh-my-zsh/custom/themes/powerlevel10k
    git pull
    cd $HOME/dotfiles
fi

# Install additional zsh plugins not included with Oh My Zsh
for r in zsh-autosuggestions zsh-syntax-highlighting; do
    if [[ ! -d $HOME/.oh-my-zsh/custom/plugins/$r ]]; then
        echo "Installing $r..."
        git clone --depth=1 https://github.com/zsh-users/$r $HOME/.oh-my-zsh/custom/plugins/$r
    else
        echo "$r already installed, updating..."
        cd $HOME/.oh-my-zsh/custom/plugins/$r
        git pull
        cd $HOME/dotfiles
    fi
done

# Link custom .zsh files to Oh My Zsh custom folder
for f in custom/*; do
    echo "Linking custom .zsh files..."
    ln -sf $HOME/dotfiles/$f $HOME/.oh-my-zsh/$f
done

# Link $HOME dotfiles
echo "Linking files to home directory..."
for f in *; do
    if [[ $f == "README.md" || $f == "bootstrap" ]]; then
        echo "" # HACK: special files, nothing to do here
    elif [[ -d $f ]]; then
        echo "" # HACK: directories, nothing to do here
    else
        ln -sf $HOME/dotfiles/$f $HOME/.$f
    fi
done

# Setup SSH
echo "Linking ssh files..."
ln -sf $HOME/dotfiles/ssh $HOME/.ssh
mkdir -p $HOME/.ssh/config.d

# Restore configs with mackup
echo "Linking mackup config and restoring files..."
ln -sf $HOME/dotfiles/mackup $HOME/.mackup
mackup restore

# Vim setup
if [[ ! -d $HOME/.vim/pack/packager/opt/vim-packager ]]; then
    echo "Installing vim-packager..."
    git clone --depth=1 https://github.com/kristijanhusak/vim-packager $HOME/.vim/pack/packager/opt/vim-packager
else
    echo "vim-packager already installed, updating..."
    cd $HOME/.vim/pack/packager/opt/vim-packager
    git pull
    cd $HOME/dotfiles
fi

# Change the users default shell
echo "Changing the default shell..."
sudo chsh -s /usr/local/bin/zsh $USER
