tap "garethr/kubeval"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "johanhaleby/kubetail"
tap "mveritym/mel"
brew "ack"
brew "python"
brew "awscli"
brew "bash"
brew "cmake"
brew "coreutils"
brew "curl"
brew "gcc"
brew "python@2"
brew "git"
brew "gnupg"
brew "kops"
brew "kube-ps1"
brew "kubectx"
brew "kubernetes-helm"
brew "kustomize"
brew "libpq"
brew "mas"
brew "mysql-client"
brew "neovim"
brew "nodenv"
brew "rbenv"
brew "tig"
brew "watch"
brew "wget"
brew "zsh"
brew "garethr/kubeval/kubeval"
brew "johanhaleby/kubetail/kubetail"
brew "mveritym/mel/kubedecode"
cask "adobe-acrobat-reader"
cask "daisydisk"
cask "docker"
cask "firefox"
cask "font-inconsolata-nerd-font-mono"
cask "google-chrome"
cask "google-drive-file-stream"
cask "insomnia"
cask "istat-menus"
cask "iterm2"
cask "logitech-options"
cask "microsoft-office"
cask "ngrok"
cask "postico"
cask "sequel-pro"
cask "spectacle"
cask "teamviewer"
cask "visual-studio-code"
cask "vlc"
cask "vnc-viewer"
mas "LastPass", id: 926036361
mas "Microsoft Remote Desktop", id: 1295203466
mas "Slack", id: 803453959
mas "SonicWall Mobile Connect", id: 822514576
mas "Unsplash Wallpapers", id: 1284863847
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
