tap "homebrew/bundle"
brew "ack"
brew "asdf"
brew "bash"
brew "cmake"
brew "coreutils"
brew "curl"
brew "fzf"
brew "git"
brew "gnupg"
brew "jq"
brew "libpq"
brew "mas"
brew "neovim"
brew "pinentry"
brew "pinentry-mac"
brew "pkg-config"
brew "telnet"
brew "tig"
brew "unzip"
brew "watch"
brew "wget"
brew "z"
brew "zsh"
cask "1password"
cask "1password-cli"
cask "bartender"
cask "battery"
cask "discord"
cask "docker"
cask "firefox"
cask "font-fira-code-nerd-font"
cask "google-chrome"
cask "istat-menus"
cask "iterm2"
cask "karabiner-elements"
cask "logi-options-plus"
cask "meetingbar"
cask "obsidian"
cask "private-internet-access"
cask "rectangle"
cask "tableplus"
cask "visual-studio-code"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Microsoft Excel", id: 462058435
mas "Microsoft Word", id: 462054704
mas "OneDrive", id: 823766827
mas "Parcel", id: 639968404
mas "Slack", id: 803453959
mas "SonicWall Mobile Connect", id: 822514576
mas "WireGuard", id: 1451685025
