tap "buo/cask-upgrade"
tap "drone/drone"
tap "garethr/kubeval"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "johanhaleby/kubetail"
tap "mveritym/mel"
tap "weaveworks/tap"
# Search tool like grep, but optimized for programmers
brew "ack"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Official Amazon AWS command-line interface
brew "awscli"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Command-line tool to access Weave Flux, the Kubernetes GitOps operator
brew "fluxctl"
# Interpreted, interactive, object-oriented programming language
brew "python"
# Distributed revision control system
brew "git"
# Add GitHub support to git on the command-line
brew "hub"
# Production Grade K8s Installation, Upgrades, and Management
brew "kops"
# Tool that can switch between kubectl contexts easily and create aliases
brew "kubectx"
# Postgres C API library
brew "libpq"
# Keep your Mac's application settings in sync
brew "mackup"
# Mac App Store command-line interface
brew "mas"
# Open source relational database management system
brew "mysql-client@5.7"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Passphrase entry dialog utilizing the Assuan protocol
brew "pinentry"
# User interface to the TELNET protocol (built from macOS Sierra sources)
brew "telnet"
# Text interface for Git repositories
brew "tig"
# Extraction utility for .zip compressed archives
brew "unzip"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Tracks most-used directories to make cd smarter
brew "z"
# UNIX shell (command interpreter)
brew "zsh"
brew "drone/drone/drone"
# Validate your Kubernetes configurations
brew "garethr/kubeval/kubeval"
# Tail logs from multiple Kubernetes pods at the same time
brew "johanhaleby/kubetail/kubetail"
# Decode all parts of a kubernetes secret, no more copypasting!
brew "mveritym/mel/kubedecode"
# The official CLI for Amazon EKS
brew "weaveworks/tap/eksctl"
cask "aerial"
cask "authy"
cask "balenaetcher"
cask "calibre"
cask "daisydisk"
cask "docker"
cask "firefox"
cask "font-firacode-nerd-font-mono"
cask "font-jetbrains-mono"
cask "forklift"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive-file-stream"
cask "gpg-suite-no-mail"
cask "insomnia"
cask "istat-menus"
cask "iterm2"
cask "keepassxc"
cask "lastpass"
cask "logitech-options"
cask "parsec"
cask "plex-media-player"
cask "private-internet-access"
cask "rectangle"
cask "skype"
cask "steam"
cask "tableplus"
cask "teamviewer"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "vnc-viewer"
cask "zoomus"
mas "Debit & Credit", id: 882637653
mas "Microsoft Excel", id: 462058435
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "OneDrive", id: 823766827
mas "Parcel", id: 639968404
mas "Slack", id: 803453959
mas "SonicWall Mobile Connect", id: 822514576
mas "Unsplash Wallpapers", id: 1284863847
mas "WhatsApp", id: 1147396723
